# Generated by Django 2.1 on 2018-08-15 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_publisher_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='书名')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Publisher')),
            ],
            options={
                'verbose_name': '书',
                'verbose_name_plural': '书',
            },
        ),
    ]
